### ISSUE TITLE
Add perl version checking in test suite

### ISSUE THREAD

**Issue by socketpair** [openresty/sregex#11]
```
t/03-pcre-testinput1-02.t .. 211/? 
#   Failed test 'TEST 37: testinput1:113 - bad regex: ^\ca\cA\c[\c{\c:: Use ";" instead of "\c{" at t/SRegex.pm line 162.
# '
#   at t/SRegex.pm line 166.
# Looks like you failed 1 test of 359.
t/03-pcre-testinput1-02.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/359 subtests 
t/03-pcre-testinput1-03.t .. ok     
```

**Comment by agentzh** [comment]
@socketpair Seems like you're using a recent version of perl to run these tests. The tests on the master branch requires perl 5.16.x (like 5.16.2) at the moment.

**Comment by socketpair** [comment]
Anyway, add perl version range checking in tests ( ,= SOME_VER or >= SOME_VER)

**Comment by agentzh** [comment]
@socketpair Those tests are imported directly from PCRE and I think we just need to skip those tests in the PCRE test suite importer (in the file `util/pcre_tests.pl` of this repos).

**Comment by agentzh** [comment]
@socketpair Well, just fixed in git master. Now both perl 5.16.2 and perl 5.24.0 can run the whole sregex test suite without failures on my side :)
