### ISSUE TITLE
`make test` requires several Perl modules that don't seem to be default (on Ubuntu 15.10 at least)

### ISSUE THREAD

**Issue by raincoats** [openresty/sregex#12]
Hi, thought you guys might want to know, on a fresh Ubuntu 15.10 install, `make test` generates a few dozen of these:

```
Can't locate Test/Base.pm in @INC (you may need to install the Test::Base module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at t/SRegex.pm line 6.
BEGIN failed--compilation aborted at t/SRegex.pm line 6.
Compilation failed in require at t/01-sanity-01.t line 3.
BEGIN failed--compilation aborted at t/01-sanity-01.t line 3.
t/01-sanity-01.t ...........
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
```
Fresh Ubuntu 15.10, only things I installed were things like lrzip, pv, tmux, things like that. Not a huge issue or anything, I don't think many people `make test`, and you guys might already know about this and are not really worried about it.

If anyone came here via googling the error code, installing `Test::Base`, `IPC::Run3` and `Test::LongString` with `cpan` fixed my issue.

**Comment by agentzh** [comment]
@raincoats Yeah, the test suite requires these CPAN modules. BTW, on Ubuntu, you could do something like

```
apt-get install libtest-base-perl libipc-run3-perl libtest-longstring-perl
```

which is easier and faster than running the cpan command.

**Comment by raincoats** [comment]
oh nice! cheers

**Comment by agentzh** [comment]
@raincoats BTW, this has been documented for long:

https://github.com/openresty/sregex/#test-suite

The manual has been there for a reason ;)
