### ISSUE TITLE
Question: Is it allowed to pass data of the same stream after (un)successful matching?

### ISSUE THREAD

**Issue by socketpair** [openresty/sregex#14]
Also, for example, for regex `_qwe_qwe_` and string `_qwe_qwe_qwe_qwe_`, how many matches I should see ?

**Comment by agentzh** [comment]
@socketpair You have total control over what to do next.

**Comment by socketpair** [comment]
Still not understand what will (should) happen ?

**Comment by agentzh** [comment]
@socketpair You decide what to do next. You have the complete control. You can check out the ngx_replace_filter module for various different options.

**Comment by agentzh** [comment]
Consider it resolved.
