### ISSUE TITLE
Support for single line mode

### ISSUE THREAD

**Issue by int0x2e** [openresty/sregex#17]
Hi,
Is there any chance support could be added for single-line mode? (meaning the dot token will match newlines as well when this flag is specified)
I can try my hand at adding this functionality if you'd like (any guidance you could offer would be very much appreciated!).

**Comment by agentzh** [comment]
@int0x2e The current implementation always uses the single line mode, i.e., dot always matches anything.

**Comment by int0x2e** [comment]
Yeah, you're absolutely right. I'm very sorry for the trouble!
Thank you so much for the reply. I really love using sregex! :-) (we're using it as part of the replace-filter nginx module, which is also awesome!)

Have a great day :-)

**Comment by agentzh** [comment]
Thanks! Glad you like them :)
