### ISSUE TITLE
Question about (?=pattern), (?!pattern), (?<=pattern), and (?<!pattern).

### ISSUE THREAD

**Issue by speciale** [openresty/sregex#22]
Hello;
I was trying to do this (yes)((?:(?[^no]).)*?>)
and then I found that's a to do. How can I make it work? 
Thanks for reading me.

**Comment by agentzh** [comment]
@speciale You'll have to contribute a patch for it.

**Comment by speciale** [comment]
I'm afraid I'm not able to do that. Thanks for your answer.
