### ISSUE TITLE
Versioned/tagged release?

### ISSUE THREAD

**Issue by davidjb** [openresty/sregex#23]
I'm looking at packaging sregex as an RPM and to do so would be easiest with a specific tagged release and version numbering.  I know sregex isn't yet fully stable, so even as a pre-release or unstable version number would be really helpful.  I see there's https://github.com/openresty/sregex/releases but that's quite a while back.

Thanks!

**Comment by agentzh** [comment]
@davidjb Done. Thanks!

**Comment by davidjb** [comment]
Thank you very much for being so fast!
