### ISSUE TITLE
Bad pike performance

### ISSUE THREAD

**Issue by Miniwoffer** [openresty/sregex#25]
I am experiencing bad performance and large performance drops comeparted to the complexity of the regex.

As you can see in the data bellow the performance drop from one char to two chars is huge. and the performance drop from two chars to a more advanced regex is relatively smale.

Am i doing somthing wrong in my usage of the library or is this exepected performance?

### single char
```
regex:       `a`
throughput:   ~867 MiB/s 
cpu_time:     sre_vm_pike_exec ~23%
```
### two chars
```
regex:        `aa`
throughput:   ~82 MiB/s 
cpu_time:     sre_vm_pike_exec ~91%
```
### all image and script tags
```
regex:        `<img[^>]+>|<script( [^>]+)?>([^<]*)</script>`
throughput:   ~49 MiB/s
cpu_time:     sre_vm_pike_exec ~93.26%
```
## testscript
```c
#define BUFFER_SIZE 1024
#define POOL_SIZE 1024
size_t pos,c;
int fd = open(filepath,O_RDONLY);
int eof = 0;
char buffer[BUFFER_SIZE];
sre_int_t *pending_matched;
if(fd < 0) {
	exit(1);
}
sre_pool_t *pool = sre_create_pool(POOL_SIZE);
sre_vm_pike_ctx_t *ctx = sre_vm_pike_create_ctx(pool,prog,ovector,ovecsize);
for (;;) {
	c = read(fd,buffer,BUFFER_SIZE);
	if (c < BUFFER_SIZE)
		eof = 1;
	sre_int_t ret;
	char *tmpos = buffer;
go:
    ret	= sre_vm_pike_exec(ctx,tmpos,c,eof,&pending_matched);
	if(ret > 0 && ovector[1] < pos+c) {
		tmpos += ovector[1];
		c -= ovector[1];
		pos += ovector[1];
		goto go;
	}
	pos += c;
	fprintf(stdout,"%.*s",c,buffer);
	if(eof)
		exit(0);
}
```

## testdata

[CUNY webpage source](http://www2.cuny.edu/) repeated until it made a 1.1G file

**Comment by agentzh** [comment]
@Miniwoffer Yes, it's expected. The Pike VM currently is not optimized at all. There's big room for optimizations.

**Comment by Miniwoffer** [comment]
Thanks for the answer @agentzh, can you make an educated guess on how much performance improvement I could experience with some optimization.

**Comment by agentzh** [comment]
@Miniwoffer It would be several times to orders of magnitude according to our initial experiments and benchmarks, depending on the data input and/or the regex patterns.
